AWSTemplateFormatVersion: '2010-09-09'
Description: Frontend CloudFormation stack for FocusQ

Parameters:
  CertificateArn:
    Type: String
    AllowedPattern: "arn:aws:acm:.*"
    ConstraintDescription: Must be a valid ACM ARN from the same region as the current stack
    Description: ARN of ACM SSL certificate for focusq.rocksci-apps.xyz

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html # For Angular routing to work
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Project
          Value: focusq
        - Key: Name
          Value: focusq-frontend

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt FrontendBucket.WebsiteURL]]
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
        - focusq.rocksci-apps.xyz
        - api.focusq.rocksci-apps.xyz
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          DefaultTTL: 86400 # 1 day in seconds
          MaxTTL: 31536000 # 1 year in seconds
          MinTTL: 0
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
      Tags:
        - Key: Project
          Value: focusq
        - Key: Name
          Value: focusq-frontend-cloudfront

Outputs:
  FrontendBucket:
    Description: Name of website bucket
    Value: !Ref FrontendBucket
    Export:
      Name: FocusqFrontendBucket